web:
  build: .
  dockerfile: nginxDockerfile

  volumes_from:
    - node
  working_dir: /app/code/public
  ports:
    - "8800:80"
  mem_limit: 50m


flask:
  build: .
  dockerfile: pythonDockerfile
  volumes:
    - ./canteen2:/back
  working_dir: /back
  environment:
    - SALT=nuegNurlOshusabCuWasBikvu
    - SECRET_KEY=whotVaijIrEcveybsOgNelfac
  ports:
    - "5000:5000"
  links:
   - db
  mem_limit: 256m


node:
  build: .
  dockerfile: nodeDockerfile
  volumes:
    - ./app/package.json:/app/package.json
    - ./app/bower.json:/app/bower.json
    - ./app:/app/code
  working_dir: /app/code
  command: gulp
  environment:
    - PROD_IP=188.166.36.35
    - DEV_IP=localhost
  mem_limit: 100m


db:
  image: postgres
  environment:
    - POSTGRES_USER=WeCeheerdEtvicsOgjotenwof
    - POSTGRES_PASSWORD=gadJesEttOditneogulrijvok
  mem_limit: 50m
