web:
  build: .
  dockerfile: nginxDockerfile

  volumes_from:
    - node
  working_dir: /app/code/public
  ports:
    - "8800:80"

flask:
  build: .
  dockerfile: pythonDockerfile
  volumes:
    - ./canteen2:/back
  working_dir: /back
  environment:
    - SALT=nuegNurlOshusabCuWasBikvu
    - SECRET_KEY=whotVaijIrEcveybsOgNelfac
  expose:
    - "5000"
  ports:
    - "5000:5000"
  links:
   - db

node:
  build: .
  dockerfile: nodeDockerfile
  volumes:
    - ./app/package.json:/app/package.json
    - ./app/bower.json:/app/bower.json
    - ./app:/app/code
  working_dir: /app/code
  command: gulp
  links:
    - flask
  mem_limit: "300m"


db:
  image: postgres
  environment:
    - POSTGRES_USER=WeCeheerdEtvicsOgjotenwof
    - POSTGRES_PASSWORD=gadJesEttOditneogulrijvok
