web:
  build: .
  dockerfile: nginxDockerfile

  volumes_from:
    - node
  working_dir: /usr/share/nginx/html
  ports:
    - "8800:80"

flask:
  build: .
  dockerfile: pythonDockerfile
  volumes:
    - ./canteen2:/back
  working_dir: /back
  expose:
    - "5000"
  ports:
    - "5000:5000"
  links:
   - db

node:
  build: .
  dockerfile: nodeDockerfile
  volumes:
    - ./app:/app/code
  links:
    - flask
  working_dir: /app/code
  command: gulp

db:
  image: postgres
  environment:
    - POSTGRES_USER=pg_root
    - POSTGRES_PASSWORD=canteen_cool_pass
