web:
  image: nginx

  volumes_from:
    - node

  volumes:
    - /app/public:/usr/share/nginx/html

  working_dir: /usr/share/nginx/html

  ports:
    - "8800:80"

flask:
  build: .
  dockerfile: pythonDockerfile

  volumes:
    - ./canteen2:/app

  working_dir: /app

  expose:
    - "5000"

  links:
   - db

node:
  build: .
  dockerfile: nodeDockerfile
  volumes:
    - ./app:/app

  links:
    - flask

db:
  image: postgres
  environment:
    - POSTGRES_USER=pg_root
    - POSTGRES_PASSWORD=canteen_cool_pass
