web:
  build: .
  dockerfile: pythonDockerfile

  volumes:
    - ./canteen2:/app

  working_dir: /app

  ports:
    - "5000:5000"

  expose:
    - "5000"

  links:
   - db

node:
  build: .
  dockerfile: nodeDockerfile
  volumes:
    - ./app:/app

  ports:
    - "8800:8080"

  command: gulp

db:
  image: postgres
  environment:
    - POSTGRES_USER=pg_root
    - POSTGRES_PASSWORD=canteen_cool_pass
